version: '3'

services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-all-in-one
    restart: always
    ports:
      - "9411:9411"

  goapp:
    build:
      dockerfile: Dockerfile
      context: ./cep_service
    ports:
      - "8080:8080"
    environment:
      - WEB_SERVER_PORT=:8080
      - BASE_URL=http://goapi:8000/weather
      - ZIPKIN_URL=http://zipkin-all-in-one:9411/api/v2/spans
    command: sh -c "/weather_service"
    depends_on:
      - zipkin-all-in-one

  goapi:
    build:
      dockerfile: Dockerfile
      context: ./cep_api
    ports:
      - "8000:8000"
    environment:
      - WEB_SERVER_PORT=:8000
      - API_KEY=4b9fd53245c44d7e9da15444240108
      - ZIPKIN_URL=http://zipkin-all-in-one:9411/api/v2/spans
    command: sh -c "/weather_api"
    depends_on:
      - zipkin-all-in-one