version: '3'

services:
  jaeger-all-in-one:
    image: "jaegertracing/all-in-one:latest"
    restart: "always"
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    container_name: "prometheus"
    image: "prom/prometheus:latest"
    restart: "always"
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  otel-collector:
    image: "otel/opentelemetry-collector:latest"
    restart: "always"
    command:
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"

  goapp:
    build:
      dockerfile: Dockerfile_Service
      context: .
    ports:
      - "8080:8080"
    environment:
      - REQUEST_NAME_OTEL=cep-service-request
      - OTEL_SERVICE_NAME=cep-service
      - OTEL_EXPORTER_ODPL_ENDPOINT=otel-collector:4317
      - WEB_SERVER_PORT=:8080
      - BASE_URL="http://127.0.0.1:8000/weather"
    command: sh -c "/weather_service"
    depends_on:
      - prometheus
      - jaeger-all-in-one
      - otel-collector

  goapi:
    build:
      dockerfile: Dockerfile_API
      context: .
    ports:
      - "8000:8000"
    environment:
      - REQUEST_NAME_OTEL=cep-service-request
      - OTEL_SERVICE_NAME=cep-service
      - OTEL_EXPORTER_ODPL_ENDPOINT=otel-collector:4317
      - WEB_SERVER_PORT=:8000
      - API_KEY=4b9fd53245c44d7e9da15444240108
    command: sh -c "/weather_api"
    depends_on:
      - prometheus
      - jaeger-all-in-one
      - otel-collector