// Code generated by MockGen. DO NOT EDIT.
// Source: ./cep_api/internal/infra/gateway/gateway.go

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWeatherGatewayInterface is a mock of WeatherGatewayInterface interface.
type MockWeatherGatewayInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherGatewayInterfaceMockRecorder
}

// MockWeatherGatewayInterfaceMockRecorder is the mock recorder for MockWeatherGatewayInterface.
type MockWeatherGatewayInterfaceMockRecorder struct {
	mock *MockWeatherGatewayInterface
}

// NewMockWeatherGatewayInterface creates a new mock instance.
func NewMockWeatherGatewayInterface(ctrl *gomock.Controller) *MockWeatherGatewayInterface {
	mock := &MockWeatherGatewayInterface{ctrl: ctrl}
	mock.recorder = &MockWeatherGatewayInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherGatewayInterface) EXPECT() *MockWeatherGatewayInterfaceMockRecorder {
	return m.recorder
}

// GetWeather mocks base method.
func (m *MockWeatherGatewayInterface) GetWeather(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeather", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeather indicates an expected call of GetWeather.
func (mr *MockWeatherGatewayInterfaceMockRecorder) GetWeather(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeather", reflect.TypeOf((*MockWeatherGatewayInterface)(nil).GetWeather), ctx)
}

// ValidateLocation mocks base method.
func (m *MockWeatherGatewayInterface) ValidateLocation(ctx context.Context, cep string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLocation", ctx, cep)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateLocation indicates an expected call of ValidateLocation.
func (mr *MockWeatherGatewayInterfaceMockRecorder) ValidateLocation(ctx, cep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLocation", reflect.TypeOf((*MockWeatherGatewayInterface)(nil).ValidateLocation), ctx, cep)
}
